api_platform:
  title: "OneBot CMS API Documentation"
  version: "0.0.1"
  show_webby: false
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  formats:
    json:
      mime_types: ["application/json"]
    jsonld:
      mime_types: ["application/ld+json"]
  patch_formats:
    json: ["application/json"]
  eager_loading:
    force_eager: true
    max_joins: 50
  enable_swagger_ui: true
  swagger:
    versions: [3]
    api_keys:
      apiKey:
        name: Authorization
        type: header
  #https://api-platform.com/docs/core/performance/
  # http_cache:
  #   invalidation:
  #     enabled: true
  # public: true
  defaults:
    cache_headers:
      max_age: 0
      shared_max_age: 3600
      vary: ["Content-Type", "Authorization", "Origin"]
    iri_only: true
    pagination_client_enabled: true
    pagination_client_items_per_page: true
  collection:
    pagination:
      enabled_parameter_name: pagination
      page_parameter_name: _page
      items_per_page_parameter_name: itemsPerPage
    exists_parameter_name: "not_null" # the URL query parameter to use is now "not_null"
