/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

/* MENUS */
export const GET_MENUS = "GET_MENUS";
export const GET_MENUS_ERROR = "GET_MENUS_ERROR";
export const GET_MENUS_SUCCESS = "GET_MENUS_SUCCESS";
export const GET_MENU = "GET_MENU";
export const GET_MENU_ERROR = "GET_MENU_ERROR";
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS";
export const CREATE_MENU = "CREATE_MENU";
export const CREATE_MENU_SUCCESS = "CREATE_MENU_SUCCESS";
export const CREATE_MENU_ERROR = "CREATE_MENU_NODE_ERROR";
export const CREATE_MENU_NODE = "CREATE_MENU_NODE";
export const CREATE_MENU_NODE_SUCCESS = "CREATE_MENU_NODE_SUCCESS";
export const CREATE_MENU_NODE_ERROR = "CREATE_MENU_NODE_ERROR";
export const REMOVE_MENU_NODE = "REMOVE_MENU_NODE";
export const REMOVE_MENU_NODE_SUCCESS = "REMOVE_MENU_NODE_SUCCESS";
export const REMOVE_MENU_NODE_ERROR = "REMOVE_MENU_NODE_ERROR";
export const UPDATE_MENU_NODE = "UPDATE_MENU_NODE";
export const UPDATE_MENU_NODE_SUCCESS = "UPDATE_MENU_NODE_SUCCESS";
export const UPDATE_MENU_NODE_ERROR = "UPDATE_MENU_NODE_ERROR";
export const PUBLISH_MENU_ERROR = "PUBLISH_MENU_ERROR";
export const PUBLISH_MENU_SUCCESS = "PUBLISH_MENU_SUCCESS";
export const PUBLISH_MENU = "PUBLISH_MENU";

/* CONTENT */
export const GET_CONTENT = "GET_CONTENT";
export const GET_CONTENT_ERROR = "GET_CONTENT_ERROR";
export const GET_CONTENT_SUCCESS = "GET_CONTENT_SUCCESS";
export const GET_CONTENTS = "GET_CONTENTS";
export const GET_CONTENTS_ERROR = "GET_CONTENTS_ERROR";
export const GET_CONTENTS_SUCCESS = "GET_CONTENTS_SUCCESS";
export const CREATE_CONTENT = "CREATE_CONTENT";
export const CREATE_CONTENT_SUCCESS = "CREATE_CONTENT_SUCCESS";
export const CREATE_CONTENT_ERROR = "CREATE_CONTENT_ERROR";
export const REMOVE_CONTENT = "REMOVE_CONTENT";
export const REMOVE_CONTENT_ERROR = "REMOVE_CONTENT_ERROR";
export const REMOVE_CONTENT_SUCCESS = "REMOVE_CONTENT_SUCCESS";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const UPDATE_CONTENT_ERROR = "UPDATE_CONTENT_ERROR";
export const UPDATE_CONTENT_SUCCESS = "UPDATE_CONTENT_SUCCESS";
export const UPDATE_CONTENT_ITEM = "UPDATE_CONTENT_ITEM";
export const CREATE_VARIANT = "CREATE_VARIANT";
export const CREATE_VARIANT_ERROR = "CREATE_VARIANT_ERROR";
export const CREATE_VARIANT_SUCCESS = "CREATE_VARIANT_SUCCESS";
export const UPDATE_VARIANT = "UPDATE_VARIANT";
export const UPDATE_VARIANT_ERROR = "UPDATE_VARIANT_ERROR";
export const UPDATE_VARIANT_SUCCESS = "UPDATE_VARIANT_SUCCESS";
export const REMOVE_VARIANT = "REMOVE_VARIANT";
export const REMOVE_VARIANT_ERROR = "REMOVE_VARIANT_ERROR";
export const REMOVE_VARIANT_SUCCESS = "REMOVE_VARIANT_SUCCESS";
export const CREATE_CONTENT_ITEM_ERROR = "CREATE_CONTENT_ITEM_ERROR";
export const CREATE_CONTENT_ITEM_SUCCESS = "CREATE_CONTENT_ITEM_SUCCESS";
export const CREATE_CONTENT_ITEM = "CREATE_CONTENT_ITEM";
export const UPDATE_CONTENT_TEXT_ITEM_ERROR = "UPDATE_CONTENT_TEXT_ITEM_ERROR";
export const UPDATE_CONTENT_TEXT_ITEM_SUCCESS =
  "UPDATE_CONTENT_TEXT_ITEM_SUCCESS";
export const UPDATE_CONTENT_TEXT_ITEM = "UPDATE_CONTENT_TEXT_ITEM";
export const REMOVE_CONTENT_TEXT_ITEM_ERROR = "REMOVE_CONTENT_TEXT_ITEM_ERROR";
export const REMOVE_CONTENT_TEXT_ITEM_SUCCESS =
  "REMOVE_CONTENT_TEXT_ITEM_SUCCESS";
export const REMOVE_CONTENT_TEXT_ITEM = "REMOVE_CONTENT_TEXT_ITEM";

/* LANGUAGE */
export const GET_LANGUAGE = "GET_LANGUAGE";
export const GET_LANGUAGE_ERROR = "GET_LANGUAGE_ERROR";
export const GET_LANGUAGE_SUCCESS = "GET_LANGUAGE_SUCCESS";
export const GET_LANGUAGES = "GET_LANGUAGES";
export const GET_LANGUAGES_ERROR = "GET_LANGUAGES_ERROR";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";
export const CREATE_LANGUAGE = "CREATE_LANGUAGE";
export const CREATE_LANGUAGE_SUCCESS = "CREATE_LANGUAGE_SUCCESS";
export const CREATE_LANGUAGE_ERROR = "CREATE_LANGUAGE_ERROR";
export const REMOVE_LANGUAGE = "REMOVE_LANGUAGE";
export const REMOVE_LANGUAGE_ERROR = "REMOVE_LANGUAGE_ERROR";
export const REMOVE_LANGUAGE_SUCCESS = "REMOVE_LANGUAGE_SUCCESS";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const UPDATE_LANGUAGE_ERROR = "UPDATE_LANGUAGE_ERROR";
export const UPDATE_LANGUAGE_SUCCESS = "UPDATE_LANGUAGE_SUCCESS";

/* SERVICE */
export const GET_SERVICE = "GET_SERVICE";
export const GET_SERVICE_ERROR = "GET_SERVICE_ERROR";
export const GET_SERVICE_SUCCESS = "GET_SERVICE_SUCCESS";
export const GET_SERVICES = "GET_SERVICES";
export const GET_SERVICES_ERROR = "GET_SERVICES_ERROR";
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const CREATE_SERVICE = "CREATE_SERVICE";
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const CREATE_SERVICE_ERROR = "CREATE_SERVICE_ERROR";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const REMOVE_SERVICE_ERROR = "REMOVE_SERVICE_ERROR";
export const REMOVE_SERVICE_SUCCESS = "REMOVE_SERVICE_SUCCESS";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const UPDATE_SERVICE_ERROR = "UPDATE_SERVICE_ERROR";
export const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS";
export const CREATE_QUESTION_VALIDATION_ERROR =
  "CREATE_QUESTION_VALIDATION_ERROR";
export const CREATE_QUESTION_VALIDATION_SUCCESS =
  "CREATE_QUESTION_VALIDATION_SUCCESS";
export const CREATE_QUESTION_VALIDATION = "CREATE_QUESTION_VALIDATION";
export const REMOVE_QUESTION_VALIDATION_ERROR =
  "REMOVE_QUESTION_VALIDATION_ERROR";
export const REMOVE_QUESTION_VALIDATION_SUCCESS =
  "REMOVE_QUESTION_VALIDATION_SUCCESS";
export const REMOVE_QUESTION_VALIDATION = "REMOVE_QUESTION_VALIDATION";
export const UPDATE_QUESTION_VALIDATION_ERROR =
  "UPDATE_QUESTION_VALIDATION_ERROR";
export const UPDATE_QUESTION_VALIDATION_SUCCESS =
  "UPDATE_QUESTION_VALIDATION_SUCCESS";
export const UPDATE_QUESTION_VALIDATION = "UPDATE_QUESTION_VALIDATION";
export const CREATE_QUESTION_ERROR = "CREATE_QUESTION_ERROR";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION = "CREATE_QUESTION";
export const REMOVE_QUESTION_ERROR = "REMOVE_QUESTION_ERROR";
export const REMOVE_QUESTION_SUCCESS = "REMOVE_QUESTION_SUCCESS";
export const REMOVE_QUESTION = "REMOVE_QUESTION";
export const UPDATE_QUESTION_ERROR = "UPDATE_QUESTION_ERROR";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION = "UPDATE_QUESTION";

/* ADMIN USERS */
export const GET_BOT_USERS = "GET_BOT_USERS";
export const GET_BOT_USERS_ERROR = "GET_BOT_USERS_ERROR";
export const GET_BOT_USERS_SUCCESS = "GET_BOT_USERS_SUCCESS";
export const GET_BOT_USER = "GET_BOT_USER";
export const GET_BOT_USER_ERROR = "GET_BOT_USERS_ERROR";
export const GET_BOT_USER_SUCCESS = "GET_BOT_USERS_SUCCESS";
export const CREATE_BOT_USER = "CREATE_BOT_USER";
export const CREATE_BOT_USER_SUCCESS = "CREATE_BOT_USER_SUCCESS";
export const CREATE_BOT_USER_ERROR = "CREATE_BOT_USER_ERROR";
export const REMOVE_BOT_USER = "REMOVE_BOT_USER";
export const REMOVE_BOT_USER_ERROR = "REMOVE_BOT_USER_ERROR";
export const REMOVE_BOT_USER_SUCCESS = "REMOVE_BOT_USER_SUCCESS";
export const UPDATE_BOT_USER = "UPDATE_BOT_USER";
export const UPDATE_BOT_USER_ERROR = "UPDATE_BOT_USER_ERROR";
export const UPDATE_BOT_USER_SUCCESS = "UPDATE_BOT_USER_SUCCESS";

/* CHANNELS */
export const GET_CHANNEL = "GET_CHANNEL";
export const GET_CHANNEL_ERROR = "GET_CHANNEL_ERROR";
export const GET_CHANNEL_SUCCESS = "GET_CHANNEL_SUCCESS";
export const GET_CHANNELS = "GET_CHANNELS";
export const GET_CHANNELS_ERROR = "GET_CHANNELS_ERROR";
export const GET_CHANNELS_SUCCESS = "GET_CHANNELS_SUCCESS";
export const CREATE_CHANNEL = "CREATE_CHANNEL";
export const CREATE_CHANNEL_SUCCESS = "CREATE_CHANNEL_SUCCESS";
export const CREATE_CHANNEL_ERROR = "CREATE_CHANNEL_ERROR";
export const REMOVE_CHANNEL = "REMOVE_CHANNEL";
export const REMOVE_CHANNEL_ERROR = "REMOVE_CHANNEL_ERROR";
export const REMOVE_CHANNEL_SUCCESS = "REMOVE_CHANNEL_SUCCESS";
export const UPDATE_CHANNEL = "UPDATE_CHANNEL";
export const UPDATE_CHANNEL_ERROR = "UPDATE_CHANNEL_ERROR";
export const UPDATE_CHANNEL_SUCCESS = "UPDATE_CHANNEL_SUCCESS";

/* VALIDATIONS */
export const GET_VALIDATION = "GET_VALIDATION";
export const GET_VALIDATION_ERROR = "GET_VALIDATION_ERROR";
export const GET_VALIDATION_SUCCESS = "GET_VALIDATION_SUCCESS";
export const GET_VALIDATIONS = "GET_VALIDATIONS";
export const GET_VALIDATIONS_ERROR = "GET_VALIDATIONS_ERROR";
export const GET_VALIDATIONS_SUCCESS = "GET_VALIDATIONS_SUCCESS";
export const CREATE_VALIDATION = "CREATE_VALIDATION";
export const CREATE_VALIDATION_SUCCESS = "CREATE_VALIDATION_SUCCESS";
export const CREATE_VALIDATION_ERROR = "CREATE_VALIDATION_ERROR";
export const REMOVE_VALIDATION = "REMOVE_VALIDATION";
export const REMOVE_VALIDATION_ERROR = "REMOVE_VALIDATION_ERROR";
export const REMOVE_VALIDATION_SUCCESS = "REMOVE_VALIDATION_SUCCESS";
export const UPDATE_VALIDATION = "UPDATE_VALIDATION";
export const UPDATE_VALIDATION_ERROR = "UPDATE_VALIDATION_ERROR";
export const UPDATE_VALIDATION_SUCCESS = "UPDATE_VALIDATION_SUCCESS";
export const REMOVE_VALIDATION_ATTRIBUTE_ERROR =
  "REMOVE_VALIDATION_ATTRIBUTE_ERROR";
export const REMOVE_VALIDATION_ATTRIBUTE_SUCCESS =
  "REMOVE_VALIDATION_ATTRIBUTE_SUCCESS";
export const REMOVE_VALIDATION_ATTRIBUTE = "REMOVE_VALIDATION_ATTRIBUTE";
export const UPDATE_VALIDATION_ATTRIBUTE_ERROR =
  "UPDATE_VALIDATION_ATTRIBUTE_ERROR";
export const UPDATE_VALIDATION_ATTRIBUTE_SUCCESS =
  "UPDATE_VALIDATION_ATTRIBUTE_SUCCESS";
export const UPDATE_VALIDATION_ATTRIBUTE = "UPDATE_VALIDATION_ATTRIBUTE";
export const GET_VALIDATION_ATTRIBUTE_ERROR = "GET_VALIDATION_ATTRIBUTE_ERROR";
export const GET_VALIDATION_ATTRIBUTE_SUCCESS =
  "GET_VALIDATION_ATTRIBUTE_SUCCESS";
export const GET_VALIDATION_ATTRIBUTE = "GET_VALIDATION_ATTRIBUTE";
export const CREATE_VALIDATION_ATTRIBUTE_ERROR =
  "CREATE_VALIDATION_ATTRIBUTE_ERROR";
export const CREATE_VALIDATION_ATTRIBUTE_SUCCESS =
  "CREATE_VALIDATION_ATTRIBUTE_SUCCESS";
export const CREATE_VALIDATION_ATTRIBUTE = "CREATE_VALIDATION_ATTRIBUTE";
export const GET_VALIDATION_ATTRIBUTES_ERROR =
  "GET_VALIDATION_ATTRIBUTES_ERROR";
export const GET_VALIDATION_ATTRIBUTES_SUCCESS =
  "GET_VALIDATION_ATTRIBUTES_SUCCESS";
export const GET_VALIDATION_ATTRIBUTES = "GET_VALIDATION_ATTRIBUTES";

/* ADMINISTRATIVE UNITS */
export const GET_ADMINISTRATIVE_UNIT = "GET_ADMINISTRATIVE_UNIT";
export const GET_ADMINISTRATIVE_UNIT_ERROR = "GET_ADMINISTRATIVE_UNIT_ERROR";
export const GET_ADMINISTRATIVE_UNIT_SUCCESS =
  "GET_ADMINISTRATIVE_UNIT_SUCCESS";
export const GET_ADMINISTRATIVE_UNITS = "GET_ADMINISTRATIVE_UNITS";
export const GET_ADMINISTRATIVE_UNITS_ERROR = "GET_ADMINISTRATIVE_UNITS_ERROR";
export const GET_ADMINISTRATIVE_UNITS_SUCCESS =
  "GET_ADMINISTRATIVE_UNITS_SUCCESS";
export const CREATE_ADMINISTRATIVE_UNIT = "CREATE_ADMINISTRATIVE_UNIT";
export const CREATE_ADMINISTRATIVE_UNIT_SUCCESS =
  "CREATE_ADMINISTRATIVE_UNIT_SUCCESS";
export const CREATE_ADMINISTRATIVE_UNIT_ERROR =
  "CREATE_ADMINISTRATIVE_UNIT_ERROR";
export const REMOVE_ADMINISTRATIVE_UNIT = "REMOVE_ADMINISTRATIVE_UNIT";
export const REMOVE_ADMINISTRATIVE_UNIT_ERROR =
  "REMOVE_ADMINISTRATIVE_UNIT_ERROR";
export const REMOVE_ADMINISTRATIVE_UNIT_SUCCESS =
  "REMOVE_ADMINISTRATIVE_UNIT_SUCCESS";
export const UPDATE_ADMINISTRATIVE_UNIT = "UPDATE_ADMINISTRATIVE_UNIT";
export const UPDATE_ADMINISTRATIVE_UNIT_ERROR =
  "UPDATE_ADMINISTRATIVE_UNIT_ERROR";
export const UPDATE_ADMINISTRATIVE_UNIT_SUCCESS =
  "UPDATE_ADMINISTRATIVE_UNIT_SUCCESS";

/* MEDIA */
export const GET_MEDIUM = "GET_MEDIUM";
export const GET_MEDIUM_ERROR = "GET_MEDIUM_ERROR";
export const GET_MEDIUM_SUCCESS = "GET_MEDIUM_SUCCESS";
export const GET_MEDIA = "GET_MEDIA";
export const GET_MEDIA_ERROR = "GET_MEDIA_ERROR";
export const GET_MEDIA_SUCCESS = "GET_MEDIA_SUCCESS";
export const CREATE_MEDIUM = "CREATE_MEDIUM";
export const CREATE_MEDIUM_SUCCESS = "CREATE_MEDIUM_SUCCESS";
export const CREATE_MEDIUM_ERROR = "CREATE_MEDIUM_ERROR";
export const REMOVE_MEDIUM = "REMOVE_MEDIUM";
export const REMOVE_MEDIUM_ERROR = "REMOVE_MEDIUM_ERROR";
export const REMOVE_MEDIUM_SUCCESS = "REMOVE_MEDIUM_SUCCESS";
export const UPDATE_MEDIUM = "UPDATE_MEDIUM";
export const UPDATE_MEDIUM_ERROR = "UPDATE_MEDIUM_ERROR";
export const UPDATE_MEDIUM_SUCCESS = "UPDATE_MEDIUM_SUCCESS";

/* LOCATIONS */
export const GET_LOCATION = "GET_LOCATION";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_LOCATIONS_ERROR = "GET_LOCATIONS_ERROR";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const CREATE_LOCATION = "CREATE_LOCATION";
export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_ERROR = "CREATE_LOCATION_ERROR";
export const REMOVE_LOCATION = "REMOVE_LOCATION";
export const REMOVE_LOCATION_ERROR = "REMOVE_LOCATION_ERROR";
export const REMOVE_LOCATION_SUCCESS = "REMOVE_LOCATION_SUCCESS";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UPDATE_LOCATION_ERROR = "UPDATE_LOCATION_ERROR";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPLOAD_LOCATIONS = "UPLOAD_LOCATIONS";
export const UPLOAD_LOCATIONS_ERROR = "UPLOAD_LOCATIONS_ERROR";
export const UPLOAD_LOCATIONS_SUCCESS = "UPLOAD_LOCATIONS_SUCCESS";
export const DOWNLOAD_LOCATIONS = "DOWNLOAD_LOCATIONS";
export const DOWNLOAD_LOCATIONS_ERROR = "DOWNLOAD_LOCATIONS_ERROR";
export const DOWNLOAD_LOCATIONS_SUCCESS = "DOWNLOAD_LOCATIONS_SUCCESS";
export const DOWNLOAD_LOCATIONS_TEMPLATE = "DOWNLOAD_LOCATIONS_TEMPLATE";
export const DOWNLOAD_LOCATIONS_TEMPLATE_ERROR =
  "DOWNLOAD_LOCATIONS_TEMPLATE_ERROR";
export const DOWNLOAD_LOCATIONS_TEMPLATE_SUCCESS =
  "DOWNLOAD_LOCATIONS_TEMPLATE_SUCCESS";

export * from "./auth/actions";
export * from "./menus/actions";
export * from "./content/actions";
export * from "./languages/actions";
export * from "./user/actions";
export * from "./channels/actions";
export * from "./validations/actions";
export * from "./administrativeUnits/actions";
export * from "./media/actions";
export * from "./locations/actions";
export * from "./service/actions";
