# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- staging

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: 'echo REACT_APP_API_ENDPOINT = $(API_ENDPOINT_STAGING) > .env'
  condition: eq(variables['build.sourceBranch'], 'refs/heads/staging')
  displayName: 'Generate staging .env'

- task: CmdLine@2
  inputs:
    script: 'echo REACT_APP_API_ENDPOINT = $(API_ENDPOINT_PROD) > .env'
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  displayName: 'Generate prod .env'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: build