#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check
api_refresh_token:
  path: /api/token/refresh
swagger_ui:
  path: /docs
  controller: api_platform.swagger_ui.action
