name: Bot API

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore: ["Farmvibes.Bot.UI/**","Farmvibes.Bot/**"]
  pull_request:
    paths-ignore: ["Farmvibes.Bot.UI/**","Farmvibes.Bot/**"]
    
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Farmvibes.Bot.API

    steps:
    - uses: actions/checkout@v3
    - name: Validate composer file
      run: |
        composer validate --no-check-publish
    - name: Install dependencies
      run: |
        composer install
    - name: run tests
      run : |
        vendor/bin/phpunit --exclude-group functional
    - name: Run static analysis
      run: |
        vendor/bin/phpstan analyse --memory-limit=1500M --error-format=github
      