name: Bot UI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      [
        "Farmvibes.Bot.API/**",
        "Farmvibes.Bot/**"
      ]
  pull_request:
    paths-ignore:
      [
        "Farmvibes.Bot.API/**",
        "Farmvibes.Bot/**"
      ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Farmvibes.Bot.UI

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: Npm install
        run: npm install --legacy-peer-deps
      - name: Linter
        run: npx eslint . --ext .js
      - name: Npm run build
        run: npm run build
        env:
         CI: ""
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      
